#!/bin/bash

set -e

POLARIS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HYPR_CONFIG="$HOME/.config/hypr"
NPROC=$(nproc)

echo "╔══════════════════════════════════════╗"
echo "║   Polaris Desktop Environment        ║"
echo "║   Install Script                     ║"
echo "╚══════════════════════════════════════╝"
echo ""

# ─── 1. Dependencies ───────────────────────
echo "▶ Installing dependencies..."
paru -S --needed --noconfirm \
    qt6-base qt6-declarative qt6-wayland \
    layer-shell-qt qt6-5compat \
    mako kitty fastfetch \
    brightnessctl fd \
    hyprpaper

echo "✓ Dependencies installed"
echo ""

# ─── 2. Build ──────────────────────────────
echo "▶ Building Polaris..."
cmake -B "$POLARIS_DIR/cmake-build-release" \
      -DCMAKE_BUILD_TYPE=Release \
      -S "$POLARIS_DIR"

cmake --build "$POLARIS_DIR/cmake-build-release" \
      --target all \
      -j "$NPROC"

echo "✓ Build complete"
echo ""

# ─── 3. Install binaries ───────────────────
echo "▶ Installing binaries to /usr/local/bin..."
sudo install -Dm755 "$POLARIS_DIR/cmake-build-release/modules/launcher/polaris_launcher"   /usr/local/bin/polaris_launcher
sudo install -Dm755 "$POLARIS_DIR/cmake-build-release/modules/taskbar/polaris_taskbar"     /usr/local/bin/polaris_taskbar
sudo install -Dm755 "$POLARIS_DIR/cmake-build-release/modules/settings/polaris_settings"   /usr/local/bin/polaris_settings
sudo install -Dm755 "$POLARIS_DIR/cmake-build-release/modules/osd/polaris_osd"             /usr/local/bin/polaris_osd
sudo install -Dm755 "$POLARIS_DIR/cmake-build-release/modules/wallpaper/polaris_wallpaper" /usr/local/bin/polaris_wallpaper

echo "✓ Binaries installed"
echo ""

# ─── 4. Dotfiles symlink ───────────────────
echo "▶ Linking dotfiles..."

# Kitty
mkdir -p "$HOME/.config/kitty"
if [ ! -e "$HOME/.config/kitty/kitty.conf" ]; then
    ln -s "$POLARIS_DIR/dotfiles/kitty/kitty.conf" "$HOME/.config/kitty/kitty.conf"
    echo "  ✓ kitty.conf linked"
else
    echo "  ⚠ kitty.conf already exists, skipping"
fi

# Fastfetch
mkdir -p "$HOME/.config/fastfetch"
if [ ! -e "$HOME/.config/fastfetch/config.jsonc" ]; then
    ln -s "$POLARIS_DIR/dotfiles/fastfetch/config.jsonc" "$HOME/.config/fastfetch/config.jsonc"
    echo "  ✓ fastfetch config linked"
else
    echo "  ⚠ fastfetch config already exists, skipping"
fi

# Mako
mkdir -p "$HOME/.config/mako"
if [ ! -e "$HOME/.config/mako/config" ]; then
    ln -s "$POLARIS_DIR/dotfiles/mako/config" "$HOME/.config/mako/config"
    echo "  ✓ mako config linked"
else
    echo "  ⚠ mako config already exists, skipping"
fi

echo "✓ Dotfiles linked"
echo ""

# ─── 5. Hyprland config ────────────────────
echo "▶ Setting up Hyprland config..."

mkdir -p "$HYPR_CONFIG/modules"

# Backup hyprland.lua trước
if [ -f "$HYPR_CONFIG/hyprland.lua" ]; then
    cp "$HYPR_CONFIG/hyprland.lua" "$HYPR_CONFIG/hyprland.lua.backup"
    echo "  ✓ Backed up hyprland.lua → hyprland.lua.backup"
fi

# Backup keybinds.lua nếu có
if [ -f "$HYPR_CONFIG/modules/keybinds.lua" ]; then
    cp "$HYPR_CONFIG/modules/keybinds.lua" "$HYPR_CONFIG/modules/keybinds.lua.backup"
    echo "  ✓ Backed up keybinds.lua → keybinds.lua.backup"
fi

# Tạo file polaris.lua cho autostart và rules
cat > "$HYPR_CONFIG/modules/polaris.lua" << 'EOF'
-- Polaris Desktop Environment
-- Auto-generated by install.sh

-- Autostart
hl.exec_once("mako")
hl.exec_once("polaris_taskbar")
hl.exec_once("polaris_wallpaper")

-- Window rules
hl.window_rule({
    match = { class = "polaris_launcher" },
    float = true,
})

hl.window_rule({
    match = { class = "polaris_settings" },
    float = true,
    move = "center center",
})
EOF

echo "  ✓ Created $HYPR_CONFIG/modules/polaris.lua"

# Thêm keybind vào keybinds.lua nếu có, không thì thêm vào polaris.lua
if [ -f "$HYPR_CONFIG/modules/keybinds.lua" ]; then
    if ! grep -q "polaris_launcher" "$HYPR_CONFIG/modules/keybinds.lua"; then
        cat >> "$HYPR_CONFIG/modules/keybinds.lua" << 'EOF'

-- Polaris keybinds
hl.bind("SUPER", "space", "exec", "polaris_launcher")
hl.bind("SUPER", "comma", "exec", "polaris_settings")
EOF
        echo "  ✓ Added keybinds to keybinds.lua"
    else
        echo "  ⚠ Polaris keybinds already exist in keybinds.lua"
    fi
else
    # Không có keybinds.lua riêng thì thêm vào polaris.lua
    cat >> "$HYPR_CONFIG/modules/polaris.lua" << 'EOF'

-- Keybinds
hl.bind("SUPER", "space", "exec", "polaris_launcher")
hl.bind("SUPER", "comma", "exec", "polaris_settings")
EOF
    echo "  ✓ Added keybinds to polaris.lua"
fi

# Thêm require polaris vào hyprland.lua nếu chưa có
if [ -f "$HYPR_CONFIG/hyprland.lua" ]; then
    if ! grep -q "polaris" "$HYPR_CONFIG/hyprland.lua"; then
        echo "" >> "$HYPR_CONFIG/hyprland.lua"
        echo "-- Polaris DE" >> "$HYPR_CONFIG/hyprland.lua"
        echo "require(\"modules/polaris\")" >> "$HYPR_CONFIG/hyprland.lua"
        echo "  ✓ Added polaris module to hyprland.lua"
    else
        echo "  ⚠ polaris already in hyprland.lua, skipping"
    fi
fi

echo "✓ Hyprland config done"

# ─── Done ──────────────────────────────────
echo "╔══════════════════════════════════════╗"
echo "║   Installation complete!             ║"
echo "║                                      ║"
echo "║   Reload Hyprland to apply:          ║"
echo "║   Ctrl + Super + Alt + R             ║"
echo "╚══════════════════════════════════════╝"