
font_family      JetBrainsMono Nerd Font
font_size        10.0


background_opacity 0.75


background_blur 1


background #0A140E
foreground #E2F0E7


selection_background #2EC4B6
selection_foreground #0A140E


window_padding_width 10
hide_window_decorations yes


copy_on_select yes